name: MCPH-Chat-Filter
version: ${version}
description: A simple chat filter for use by MCProHosting.
author: Matthew Salsamendi

main: com.mcprohosting.plugins.mcph_chat_filter.MCPHChatFilter
database: false

commands:
  setchatmode:
    description: Changes the level of allowed chat
    usage: /<command> <ChatMode>

permissions:
  mcphchatfilter.setchatmode:
    description: Sets the chat mode
    default: op